### PR TITLE
Remove pointers to the shared directory for upstream testinfra tests

### PR DESCRIPTION
**Pull request by andrew103**

### CODE REVIEW

**Comment by greg-hellings** [comment]
I'm not entirely sure about this change. I set this as the default so that those roles that do have the exact same conditions in both a Docker and VM environment can easily share the verification code. If the two conditions are not identical, then this line can be removed easily enough in the particular role tests and separate tests created. @robled and @seandst - what do you both think?

**Comment by tehsmyers** [comment]
> I'm not entirely sure about this change. I set this as the default so that those roles that do have the exact same conditions in both a Docker and VM environment can easily share the verification code.

How many roles have the exact same conditions inside and outside of docker? I don't think that's very common.

**Comment by greg-hellings** [comment]
@seandst I have yet to write one that doesn't. Things like uploading files, setting system repositories, setting mount points, installing a package, installing and configuring a service - all of these will match the same conditions in both Docker and a thick host. I struggle to think of anything other than firewalld that will be different, at least in its default configuration.

Sure, when we get to a role that we're testing multiple configurations in multiple scenarios, then there might be differences (e.g. does the webserver only serve from port 80 when configured to ignore HTTPS has a different set of tests than does it serve valid HTTPS on 443 when that's configured). But for the baseline comparison, they're almost all going to be applicable across both environments.

**Comment by tehsmyers** [comment]
For all of the scenarios you named, I don't see a single one running testinfra tests. So far, every role that I've seen with testinfra tests in it does not share those tests across scenarios. At this point, putting tests in `shared/tests` appears to be exceptional among scenarios with testinfra tests.

**Comment by greg-hellings** [comment]
`upload_files` has testinfra [tests](https://github.com/oasis-roles/upload_files/tree/master/molecule/default/tests). Its scenarios were similar enough that I completely forewent having an openstack test, but if we later need to test it works properly in a different environment (because it has a different Ansible connection plugin in use) then we would just re-use the same tests.

`system_repositories` was written before we had even figured out how to run testinfra properly and needs to be retrofitted with tests. However, it will have the exact same set of test code between all of its environments.

`jbosseap`, `kdump`, and `cockpit` merely install, configure, and start a service. The exact same code can be shared between all environments, if we want to add testinfra tests to them at all.

Overall, I think the number of roles that *don't* share tests (or have no tests at all, and thus share the empty set) will be fewer than those that do. And those that do need unique tests between the two host types can easily just delete this line in their role files. Those that want to adhere to DRY principles aren't then forced to go find the value of this setting and add it to this file.

**Comment by tehsmyers** [comment]
Are there tickets on those projects tracking all of the things that we would, will, or can do to improve the testing along these lines? I'm looking at what we have *now*, not what we might have at some point in the future. Making these plans visible would certainly affect my opinion.

**Comment by greg-hellings** [comment]
There is not, but there definitely can be.

**Comment by robled** [comment]
My humble opinion is that the pointers to 'shared' are OK by default, in that when starting a new project you can attempt to get your testinfra stuff running upstream in Travis, which may be ideal when possible.

It provides a hint that it may be possible to do, and if it's not, you can change it.  I went through this recently with the **nfs_server** role, where I tried getting the same tests going in Docker and OpenStack, but it didn't pan out.  But hey, at least I tried.

**Comment by tehsmyers** [comment]
I see this as being similar to the systemd docker stuff in #6. Rather than removing this as the default, it'd probably be better to just put a comment on it explaining that it's useful for sharing tests across scenarios, but not required.

We could also use [`additional_files_or_dirs`](https://molecule.readthedocs.io/en/latest/configuration.html#molecule.verifier.testinfra.Testinfra) instead of `directory` so that shared tests are always included by default in addition to the scenario-specific tests rather than overriding them outright (but still slap a comment on there).

**Comment by robled** [comment]
I like all those ideas. :+1:

**Comment by greg-hellings** [comment]
`additional_files_or_dirs`++++

**Pull request merged**
