### PR TITLE
Ignore Ansible Lint code 204 - line length

### PR DESCRIPTION
**Pull request by greg-hellings**
In Molecule, yamllint is already running, which checks for line length
issues. We already have ways to disable that one a per-line basis in the
file. By disabling the entire rule in Ansible Lint, we avoid having to
disable linting on whole tasks just to avoid line length problems.

### CODE REVIEW

**Comment by greg-hellings** [comment]
Addresses #11

**Review by tehsmyers — APPROVED** [review]
If you want to deduplicate stuff, a `.ansible-lint` file at the root dir of the role will be used when molecule runs if it exists. Molecule's own CI depends on this, but I'm not sure if it's documented.

**Comment by greg-hellings** [comment]
Oooooo, that is juicy. I'm thinking I'm going to go that route.

**Review by st-murray — APPROVED** [review]
I approve

**Pull request merged**
